project:
  type: rostools-theme
  render:
    - "!template/"
    - "*.qmd"
    - "*.md"

book:
  title: "Template Workshop"
  subtitle: "An opinionated template for making workshops as open educational resources"
  site-url: "https://template-workshop.rostools.org"
  repo-url: "https://github.com/rostools/template-workshop"
  chapters:
    - index.qmd
    - part: "Guide"
      chapters:
        - docs/guide/installing.qmd
        - docs/guide/using.qmd
        - docs/guide/updating.qmd
        - docs/guide/next-steps.qmd
  appendices:
    - CONTRIBUTING.md
    - CHANGELOG.md
  tools:
    - icon: github
      href: "https://github.com/rostools/template-workshop"
      aria-label: "GitHub icon: Source code"

format:
  rostools-theme-html:
    include-before-body:
    - "docs/includes/site-counter.html"

metadata-files:
  - _metadata.yml
