project:
  type: rostools-theme
  render:
    - "!template/"
    - "*.qmd"
    - "*.md"

book:
  title: "Template Workshop"
  subtitle: "An opinionated template for making workshops as open educational resources"
  site-url: "https://template-workshop.rostools.org"
  repo-url: "https://github.com/rostools/template-workshop"
  chapters:
    - index.qmd
    - docs/guide.qmd
    - CHANGELOG.md
    - CONTRIBUTING.md
  tools:
    - icon: github
      href: "https://github.com/rostools/template-workshop"
      aria-label: "GitHub icon: Source code"

format:
  rostools-theme-html:
    theme:
      - brand
    include-before-body:
    - "docs/includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

metadata-files:
  - _metadata.yml
